const opportunities = [

    // ===== INTERNSHIPS =====
    {
        title: "Web Developer Internship",
        type: "internship",
        description: "3-month internship building web applications with a local fintech startup.",
        field: "Computer Science",
        city: "Ouagadougou - Zone du Bois",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-15",
        link: "https://example.com/internship-1",
    },
    {
        title: "Data Analysis Internship",
        type: "internship",
        description: "Internship analyzing real transaction datasets in a fintech company.",
        field: "Computer Science",
        city: "Koudougou",
        latitude: 12.2529,
        longitude: -2.3625,
        deadline: "2026-08-20",
        link: "https://example.com/internship-2",
    },
    {
        title: "Mobile App Development Internship",
        type: "internship",
        description: "Internship building a mobile app for a local NGO.",
        field: "Computer Science",
        city: "Ouagadougou - Gounghin",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-05",
        link: "https://example.com/internship-3",
    },
    {
        title: "Marketing Assistant Internship",
        type: "internship",
        description: "Internship supporting digital marketing campaigns for an e-commerce company.",
        field: "Marketing",
        city: "Bobo-Dioulasso",
        latitude: 11.1771,
        longitude: -4.2979,
        deadline: "2026-08-18",
        link: "https://example.com/internship-4",
    },
    {
        title: "Project Management Internship (NGO)",
        type: "internship",
        description: "Support project coordination for a local development NGO.",
        field: "Project Management",
        city: "Ouagadougou - Tanghin",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-25",
        link: "https://example.com/internship-5",
    },

    // ===== COMPETITIONS =====
    {
        title: "National Innovation Competition",
        type: "competition",
        description: "A national contest for young entrepreneurs to pitch tech-based solutions.",
        field: "Entrepreneurship",
        city: "Bobo-Dioulasso",
        latitude: 11.1771,
        longitude: -4.2979,
        deadline: "2026-07-30",
        link: "https://example.com/competition-1",
    },
    {
        title: "Agribusiness Innovation Challenge",
        type: "competition",
        description: "A competition for solutions improving agricultural supply chains.",
        field: "Agriculture",
        city: "Bobo-Dioulasso",
        latitude: 11.1771,
        longitude: -4.2979,
        deadline: "2026-08-10",
        link: "https://example.com/competition-2",
    },
    {
        title: "Inter-University Hackathon",
        type: "competition",
        description: "48-hour hackathon bringing together students from universities nationwide.",
        field: "Computer Science",
        city: "Ouagadougou - Ouaga 2000",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-22",
        link: "https://example.com/competition-3",
    },
    {
        title: "National Cybersecurity Challenge",
        type: "competition",
        description: "A student competition focused on cybersecurity and ethical hacking skills.",
        field: "Computer Science",
        city: "Ouagadougou - Patte d'Oie",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-09-01",
        link: "https://example.com/competition-4",
    },

    // ===== TRAININGS =====
    {
        title: "Digital Marketing Training",
        type: "training",
        description: "Free 2-week training on digital marketing fundamentals for students.",
        field: "Marketing",
        city: "Ouagadougou - Dassasgho",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-01",
        link: "https://example.com/training-1",
    },
    {
        title: "Public Speaking Workshop",
        type: "training",
        description: "One-day workshop to build confidence in public speaking and presentations.",
        field: "Communication",
        city: "Ouahigouya",
        latitude: 13.5828,
        longitude: -2.4218,
        deadline: "2026-07-25",
        link: "https://example.com/training-2",
    },
    {
        title: "Youth Leadership Training",
        type: "training",
        description: "A training program to develop leadership skills among young students.",
        field: "Personal Development",
        city: "Fada N'Gourma",
        latitude: 12.0616,
        longitude: 0.3578,
        deadline: "2026-08-12",
        link: "https://example.com/training-3",
    },
    {
        title: "Web Development Bootcamp",
        type: "training",
        description: "Intensive 3-week certifying bootcamp covering HTML, CSS, JavaScript and Node.js.",
        field: "Computer Science",
        city: "Ouagadougou - Cissin",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-28",
        link: "https://example.com/training-4",
    },
    {
        title: "Personal Finance Workshop",
        type: "training",
        description: "Practical workshop on budgeting and financial planning for young adults.",
        field: "Finance",
        city: "Koudougou",
        latitude: 12.2529,
        longitude: -2.3625,
        deadline: "2026-08-08",
        link: "https://example.com/training-5",
    },

    // ===== EVENTS =====
    {
        title: "Tech Career Fair",
        type: "event",
        description: "Annual career fair connecting students with tech employers across the country.",
        field: "Computer Science",
        city: "Ouagadougou - Ouaga 2000",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-09-05",
        link: "https://example.com/event-1",
    },
    {
        title: "Renewable Energy Forum",
        type: "event",
        description: "A forum bringing together students and professionals in renewable energy.",
        field: "Engineering",
        city: "Ouagadougou - Zogona",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-09-15",
        link: "https://example.com/event-2",
    },
    {
        title: "Entrepreneurship Conference",
        type: "event",
        description: "Conference on entrepreneurship trends and opportunities in West Africa.",
        field: "Entrepreneurship",
        city: "Bobo-Dioulasso",
        latitude: 11.1771,
        longitude: -4.2979,
        deadline: "2026-09-10",
        link: "https://example.com/event-3",
    },
    {
        title: "University Open Day",
        type: "event",
        description: "Open house event where a local university presents its programs to prospective students.",
        field: "Education",
        city: "Ouagadougou - Kilwin",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-08-30",
        link: "https://example.com/event-4",
    },
    {
        title: "Student-Professional Networking Night",
        type: "event",
        description: "Informal evening event connecting students with professionals in tech and business.",
        field: "Networking",
        city: "Ouagadougou - Somgandé",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-09-12",
        link: "https://example.com/event-5",
    },
    {
        title: "National Excellence Awards Ceremony",
        type: "event",
        description: "Award ceremony recognizing top-performing students across the country.",
        field: "Education",
        city: "Ouagadougou - Ouaga 2000",
        latitude: 12.3714,
        longitude: -1.5197,
        deadline: "2026-09-20",
        link: "https://example.com/event-6",
    },

];

module.exports = opportunities;